blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/thangchung/awesome-dotnet-core/discussions
    about: For general questions, please use Discussions instead of Issues.
